# Generated by Django 3.2 on 2021-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210529_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('image', models.ImageField(default='carousel/plant.png', upload_to='carousel/')),
            ],
        ),
    ]
