# Generated by Django 3.2 on 2021-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_lightingdeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingdeal',
            name='image',
            field=models.ImageField(default='lightingdeal/plant.png', upload_to='lightingdeal/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
